title: James Kajon
description: Worcester Polytechnic Institute Senior studying Computer Science
baseurl: ''
url: https://www.jameskajon.com
permalink: slug
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
  - license
  - CNAME
  - vendor
plugins:
  - jekyll-sitemap
strict_front_matter: true
